/**
 * ErrorState Types
 * Generated by JUP Infinite Improvement System
 */

export interface ErrorState {
  id: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ErrorStateInput {
  // TODO: Define input fields
  name?: string;
  description?: string;
}

export interface ErrorStateResponse {
  success: boolean;
  data?: ErrorState;
  error?: string;
}

export type ErrorStateStatus = 'pending' | 'active' | 'completed' | 'failed';

export interface ErrorStateConfig {
  enabled: boolean;
  timeout: number;
  retries: number;
}
