/**
 * OrderProps Types
 * Generated by JUP Infinite Improvement System
 */

export interface OrderProps {
  id: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface OrderPropsInput {
  // TODO: Define input fields
  name?: string;
  description?: string;
}

export interface OrderPropsResponse {
  success: boolean;
  data?: OrderProps;
  error?: string;
}

export type OrderPropsStatus = 'pending' | 'active' | 'completed' | 'failed';

export interface OrderPropsConfig {
  enabled: boolean;
  timeout: number;
  retries: number;
}
