import React from 'react';
import PropTypes from 'prop-types';

/**
 * DataView Component
 * Generated by JUP Infinite Improvement System
 */

const DataView = ({ data, onAction, loading = false }) => {
  // TODO: Implement DataView component logic
  
  if (loading) {
    return <div>Loading DataView...</div>;
  }

  return (
    <div className="dataview-container">
      <h3>DataView</h3>
      <pre>{JSON.stringify(data, null, 2)}</pre>
      <button onClick={onAction}>
        Action
      </button>
    </div>
  );
};

DataView.propTypes = {
  data: PropTypes.object,
  onAction: PropTypes.func.isRequired,
  loading: PropTypes.bool
};

DataView.defaultProps = {
  data: {},
  loading: false
};

export default DataView;
